title: Cassandra Johnson # your name (or website title) here
logo: "/images/20220926_152111.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br>
  Tableau | SQL Server | Python
  <br> 
  Problem solving | Developing improved insights, enabling management to make better decisions 
  <br><br>
  cassandrajohnson328@gmail.com 
  <br>
  904-534-2813 
  <br><br>
  <a href="https://www.linkedin.com/in/cassandradjohnson/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-7XE4Z34LH5 # your Google Analytics tracking ID here

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7XE4Z34LH5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7XE4Z34LH5');
</script>
